In [1]:
import numpy as np

# Dados do problema
a = 0
b = 1
c = 0
d = 2

h = 0.5
k = 0.5

# Função da EDP
def f(x, y):
    return 4

# Solução exata
def exata(x, y):
    return (x - y)**2

# Condições de contorno
def inferior(x):
    return x**2

def superior(x):
    return (x - 2)**2

def esquerda(y):
    return y**2

def direita(y):
    return (y - 1)**2


nx = int((b-a)/h)
ny = int((d-c)/k)

x = np.linspace(a,b,nx+1)
y = np.linspace(c,d,ny+1)

u = np.zeros((ny+1,nx+1))

# Contornos
for i in range(nx+1):
    u[0,i] = inferior(x[i])
    u[ny,i] = superior(x[i])

for j in range(ny+1):
    u[j,0] = esquerda(y[j])
    u[j,nx] = direita(y[j])

tol = 1e-10
erro = 1

while erro > tol:

    erro = 0

    for j in range(1,ny):
        for i in range(1,nx):

            novo = (u[j,i-1]+u[j,i+1]+u[j-1,i]+u[j+1,i]-h*h*f(x[i],y[j]))/4

            erro = max(erro,abs(novo-u[j,i]))

            u[j,i]=novo

print("Solução aproximada:")
print(u)

print()

print("Solução exata:")

ue = np.zeros_like(u)

for j in range(ny+1):
    for i in range(nx+1):
        ue[j,i]=exata(x[i],y[j])

print(ue)

print()

print("Erro máximo =",np.max(np.abs(u-ue)))

Solução aproximada:
[[ 0.00000000e+00  2.50000000e-01  1.00000000e+00]
 [ 2.50000000e-01 -7.73070497e-12  2.50000000e-01]
 [ 1.00000000e+00  2.50000000e-01  0.00000000e+00]
 [ 2.25000000e+00  1.00000000e+00  2.50000000e-01]
 [ 4.00000000e+00  2.25000000e+00  1.00000000e+00]]

Solução exata:
[[0.   0.25 1.  ]
 [0.25 0.   0.25]
 [1.   0.25 0.  ]
 [2.25 1.   0.25]
 [4.   2.25 1.  ]]

Erro máximo = 7.73070496506989e-12
