## Questão 2

Utilize o **Algoritmo 12.1** para determinar uma solução aproximada da equação diferencial parcial elíptica

$$
\frac{\partial^2u}{\partial x^2}
+
\frac{\partial^2u}{\partial y^2}
=
0,
\qquad
1<x<2,\;
0<y<1.
$$

Condições de contorno

$$
u(x,0)=2\ln x,
$$

$$
u(x,1)=\ln(x^2+1),
\qquad
1\le x\le2,
$$

$$
u(1,y)=\ln(y^2+1),
$$

$$
u(2,y)=\ln(y^2+4),
\qquad
0\le y\le1.
$$

Utilize

$$
h=k=\frac13
$$

e compare os resultados com a solução exata

$$
u(x,y)=\ln(x^2+y^2).
$$


In [2]:
import numpy as np

a=1
b=2

c=0
d=1

h=1/3
k=1/3

def f(x,y):
    return 0

def exata(x,y):
    return np.log(x*x+y*y)

def inferior(x):
    return 2*np.log(x)

def superior(x):
    return np.log(x*x+1)

def esquerda(y):
    return np.log(y*y+1)

def direita(y):
    return np.log(y*y+4)

nx=int((b-a)/h)
ny=int((d-c)/k)

x=np.linspace(a,b,nx+1)
y=np.linspace(c,d,ny+1)

u=np.zeros((ny+1,nx+1))

for i in range(nx+1):
    u[0,i]=inferior(x[i])
    u[ny,i]=superior(x[i])

for j in range(ny+1):
    u[j,0]=esquerda(y[j])
    u[j,nx]=direita(y[j])

tol=1e-10
erro=1

while erro>tol:

    erro=0

    for j in range(1,ny):
        for i in range(1,nx):

            novo=(u[j,i-1]+u[j,i+1]+u[j-1,i]+u[j+1,i])/4

            erro=max(erro,abs(novo-u[j,i]))

            u[j,i]=novo

print(u)

ue=np.zeros_like(u)

for j in range(ny+1):
    for i in range(nx+1):
        ue[j,i]=exata(x[i],y[j])

print("Erro =",np.max(np.abs(u-ue)))

[[0.         0.57536414 1.02165125 1.38629436]
 [0.10536052 0.63480436 1.05999246 1.41369334]
 [0.36772478 0.79850032 1.1698209  1.49165488]
 [0.69314718 1.02165125 1.32913595 1.60943791]]
Erro = 0.0011844055243078744
